version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.5.0
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-init
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../Exercises:/opt/airflow/exercises
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__RBAC=True
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.5.0
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-init
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ../Exercises:/opt/airflow/exercises
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: scheduler

  airflow-init:
    image: apache/airflow:2.5.0
    container_name: airflow-init
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ../Exercises:/opt/airflow/exercises
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: db init

volumes:
  postgres_data:
